batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 16
model_path: Models/03_handwriting_recognition\202402282135
train_epochs: 1000
train_workers: 20
vocab: cIVe9pRLDZCbz#0YHyfodW(T2,'S)-Ja4sqF?"jNvQrMB.OE;76&5KU!8GP:ltnmh1wi3xugkA
width: 128
